// Theme definitions matching admin/src/data/themes.js
export const THEMES = [
  { id:'cartier-noir',    name:'Cartier Noir',    thumbnail:'⬛', category:'Luxury',    colors:{ bg:'#0a0a0a',bgSecondary:'#141414',bgCard:'#1a1a1a',border:'#2a2a2a',text:'#f5f0e8',textMuted:'#8a8078',accent:'#c9a84c',accentHover:'#dbb95f',navBg:'rgba(10,10,10,0.95)',buttonBg:'#c9a84c',buttonText:'#0a0a0a' }, fonts:{ heading:"'Playfair Display', Georgia, serif",body:"'Inter', system-ui, sans-serif",headingWeight:400 }, nav:{ topBar:true,topBarBg:'#c9a84c',topBarText:'#0a0a0a' }, buttons:{ radius:'2px' }, preview:{ bg:'#0a0a0a',accent:'#c9a84c',text:'#f5f0e8' } },
  { id:'graff-gold',      name:'Graff Gold',      thumbnail:'🟡', category:'Luxury',    colors:{ bg:'#1a1208',bgSecondary:'#241a0a',bgCard:'#2a1e0c',border:'#4a3010',text:'#f5e8c8',textMuted:'#a08050',accent:'#d4a843',accentHover:'#e8c060',navBg:'rgba(26,18,8,0.97)',buttonBg:'#d4a843',buttonText:'#1a1208' }, fonts:{ heading:"'Cormorant Garamond', Georgia, serif",body:"'Inter', system-ui, sans-serif",headingWeight:300 }, nav:{ topBar:true,topBarBg:'#d4a843',topBarText:'#1a1208' }, buttons:{ radius:'4px' }, preview:{ bg:'#1a1208',accent:'#d4a843',text:'#f5e8c8' } },
  { id:'blue-nile-white', name:'Blue Nile',        thumbnail:'⬜', category:'Modern',    colors:{ bg:'#ffffff',bgSecondary:'#fafaf8',bgCard:'#ffffff',border:'#e5e5e5',text:'#1a1a1a',textMuted:'#6b6b6b',accent:'#1a1a1a',accentHover:'#333333',navBg:'#ffffff',buttonBg:'#1a1a1a',buttonText:'#ffffff' }, fonts:{ heading:"'Inter', system-ui, sans-serif",body:"'Inter', system-ui, sans-serif",headingWeight:300 }, nav:{ topBar:true,topBarBg:'#1a1a1a',topBarText:'#ffffff' }, buttons:{ radius:'50px' }, preview:{ bg:'#ffffff',accent:'#1a1a1a',text:'#1a1a1a' } },
  { id:'mejuri-rose',     name:'Mejuri Rose',      thumbnail:'🌸', category:'Modern',    colors:{ bg:'#fdf8f6',bgSecondary:'#f5ede8',bgCard:'#ffffff',border:'#e8d5cc',text:'#2a1a14',textMuted:'#8a5a4a',accent:'#c07060',accentHover:'#a05040',navBg:'#fdf8f6',buttonBg:'#c07060',buttonText:'#ffffff' }, fonts:{ heading:"'Cormorant Garamond', Georgia, serif",body:"'Inter', system-ui, sans-serif",headingWeight:400 }, nav:{ topBar:false,topBarBg:'#c07060',topBarText:'#ffffff' }, buttons:{ radius:'50px' }, preview:{ bg:'#fdf8f6',accent:'#c07060',text:'#2a1a14' } },
  { id:'tejori-cream',    name:'Tejori Cream',     thumbnail:'🤎', category:'Boutique',  colors:{ bg:'#fdf6ec',bgSecondary:'#f5ebe0',bgCard:'#ffffff',border:'#e8d5bc',text:'#3d2b1a',textMuted:'#8b6f4a',accent:'#8b5e3c',accentHover:'#6b4a2e',navBg:'#fdf6ec',buttonBg:'#8b5e3c',buttonText:'#ffffff' }, fonts:{ heading:"'Playfair Display', Georgia, serif",body:"'Inter', system-ui, sans-serif",headingWeight:400 }, nav:{ topBar:true,topBarBg:'#3d2b1a',topBarText:'#f5ebe0' }, buttons:{ radius:'8px' }, preview:{ bg:'#fdf6ec',accent:'#8b5e3c',text:'#3d2b1a' } },
  { id:'dubai-gold-souk', name:'Dubai Gold Souk',  thumbnail:'🏆', category:'Boutique',  colors:{ bg:'#faf3e0',bgSecondary:'#f0e6c8',bgCard:'#ffffff',border:'#d4b896',text:'#2d1810',textMuted:'#7a4a30',accent:'#b8860b',accentHover:'#9a700a',navBg:'#2d1810',buttonBg:'#b8860b',buttonText:'#ffffff' }, fonts:{ heading:"'Playfair Display', Georgia, serif",body:"'Inter', system-ui, sans-serif",headingWeight:500 }, nav:{ topBar:true,topBarBg:'#2d1810',topBarText:'#d4b896' }, buttons:{ radius:'2px' }, preview:{ bg:'#faf3e0',accent:'#b8860b',text:'#2d1810' } },
  { id:'diamond-navy',    name:'Diamond Navy',     thumbnail:'💙', category:'Diamond',   colors:{ bg:'#0f172a',bgSecondary:'#1e293b',bgCard:'#1e293b',border:'#334155',text:'#f8fafc',textMuted:'#64748b',accent:'#3b82f6',accentHover:'#2563eb',navBg:'#0f172a',buttonBg:'#3b82f6',buttonText:'#ffffff' }, fonts:{ heading:"'Inter', system-ui, sans-serif",body:"'Inter', system-ui, sans-serif",headingWeight:600 }, nav:{ topBar:true,topBarBg:'#1e293b',topBarText:'#93bbfc' }, buttons:{ radius:'8px' }, preview:{ bg:'#0f172a',accent:'#3b82f6',text:'#f8fafc' } },
  { id:'platinum-slate',  name:'Platinum Slate',   thumbnail:'🔘', category:'Diamond',   colors:{ bg:'#f8fafc',bgSecondary:'#f1f5f9',bgCard:'#ffffff',border:'#e2e8f0',text:'#0f172a',textMuted:'#475569',accent:'#64748b',accentHover:'#475569',navBg:'#0f172a',buttonBg:'#0f172a',buttonText:'#ffffff' }, fonts:{ heading:"'Inter', system-ui, sans-serif",body:"'Inter', system-ui, sans-serif",headingWeight:400 }, nav:{ topBar:true,topBarBg:'#0f172a',topBarText:'#94a3b8' }, buttons:{ radius:'50px' }, preview:{ bg:'#f8fafc',accent:'#0f172a',text:'#0f172a' } },
  { id:'tiffany-blue',    name:'Tiffany Blue',     thumbnail:'🩵', category:'Editorial', colors:{ bg:'#f0fafa',bgSecondary:'#e0f5f5',bgCard:'#ffffff',border:'#b2e0e0',text:'#0d3333',textMuted:'#4a8888',accent:'#0ababa',accentHover:'#089898',navBg:'#0d3333',buttonBg:'#0ababa',buttonText:'#ffffff' }, fonts:{ heading:"'Playfair Display', Georgia, serif",body:"'Inter', system-ui, sans-serif",headingWeight:400 }, nav:{ topBar:true,topBarBg:'#0d3333',topBarText:'#b2e0e0' }, buttons:{ radius:'50px' }, preview:{ bg:'#f0fafa',accent:'#0ababa',text:'#0d3333' } },
  { id:'midnight-emerald',name:'Midnight Emerald', thumbnail:'💚', category:'Editorial', colors:{ bg:'#0a1a0f',bgSecondary:'#0f2218',bgCard:'#142a1c',border:'#1e4028',text:'#e8f5ec',textMuted:'#6a9878',accent:'#4caf70',accentHover:'#3d9060',navBg:'rgba(10,26,15,0.97)',buttonBg:'#4caf70',buttonText:'#0a1a0f' }, fonts:{ heading:"'Playfair Display', Georgia, serif",body:"'Inter', system-ui, sans-serif",headingWeight:400 }, nav:{ topBar:true,topBarBg:'#4caf70',topBarText:'#0a1a0f' }, buttons:{ radius:'6px' }, preview:{ bg:'#0a1a0f',accent:'#4caf70',text:'#e8f5ec' } },
];
export const getThemeById = (id) => THEMES.find(t => t.id === id) || THEMES[0];
